# numpy

위키문서 <https://wikidocs.net/217157> 에 있는 내용 중 numpy 관련 부분만 따라서 진행해 본 내용.


## 환경
- mac os, miniforge3, ml_39 가상환경
- 최초 진행일: 2025.3.12
- 요구사항
  - conda install numpy
  - conda install matplotlib
    - matplotlib 은 설치 과정 중 잠시 중단한 상태.

## numpy 기본 배열

In [11]:
import numpy as np

# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print(vec)

# 2차원 배열
mat = np.array([[10, 20, 30], [ 60, 70, 80]])
print(mat)

print('vec의 타입 :',type(vec))
print('mat의 타입 :',type(mat))

print('vec의 축의 개수 :',vec.ndim) # 축의 개수 출력
print('vec의 크기(shape) :',vec.shape) # 크기 출력

print('mat의 축의 개수 :',mat.ndim) # 축의 개수 출력
print('mat의 크기(shape) :',mat.shape) # 크기 출력


[1 2 3 4 5]
[[10 20 30]
 [60 70 80]]
vec의 타입 : <class 'numpy.ndarray'>
mat의 타입 : <class 'numpy.ndarray'>
vec의 축의 개수 : 1
vec의 크기(shape) : (5,)
mat의 축의 개수 : 2
mat의 크기(shape) : (2, 3)


## 다양한 모양의 배열 초기화

In [25]:
# 모든 값이 0인 2x3 배열 생성.
zero_mat = np.zeros((2,3))
print(f'zero:\n{zero_mat}')

# 모든 값이 1인 2x3 배열 생성.
one_mat = np.ones((2,3))
print('ones:\n' + str(one_mat))

# 모든 값이 특정 상수인 배열 생성. 이 경우 7.
same_value_mat = np.full((2,2), 7)
print('7s:\n%s' % same_value_mat)

# 대각선 값이 1이고 나머지 값이 0인 2차원 배열을 생성.
eye_mat = np.eye(3)
print('eye:\n%s' % eye_mat)

# 임의의 값으로 채워진 배열 생성
random_mat = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print('random:\n%s' % random_mat)

zero:
[[0. 0. 0.]
 [0. 0. 0.]]
ones:
[[1. 1. 1.]
 [1. 1. 1.]]
7s:
[[7 7]
 [7 7]]
eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random:
[[0.75843492 0.63522364]
 [0.71044939 0.49267834]]


## np.arange()

In [14]:
# 0부터 9까지
range_vec = np.arange(10)
print('arrange(10):\n%s' % range_vec)

# 1부터 9까지 +2씩 적용되는 범위
n = 2
range_n_step_vec = np.arange(1, 10, n)
print('arrange(1,10,2):\n%s' % range_n_step_vec)

reshape_mat = np.array(np.arange(30)).reshape((5,6))
print('reshaped:\n%s' % reshape_mat)


arrange(10):
[0 1 2 3 4 5 6 7 8 9]
arrange(1,10,2):
[1 3 5 7 9]
reshaped:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


## 슬라이싱

In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

# 첫번째 행 출력
slicing_mat = mat[0, :]
print('mat[0, :]\n%s' % slicing_mat)

# 두번째 열 출력
slicing_mat = mat[:, 1]
print('mat[:, 1]\n%s' % slicing_mat)
# 세로로 표시되는 벡터가 아니고 그냥 가로 벡터이다.

[[1 2 3]
 [4 5 6]]
mat[0, :]
[1 2 3]
mat[:, 1]
[2 5]


## 인덱싱

In [23]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

# 1행 0열의 원소
# => 0부터 카운트하므로 두번째 행 첫번째 열의 원소.
print(mat[1, 0])

# mat[[2행, 1행],[0열, 1열]]
# 각 행과 열의 쌍을 매칭하면 2행 0열, 1행 1열의 두 개의 원소.
indexing_mat = mat[[2, 1],[0, 1]]
print(indexing_mat)

print('-------')
print(mat[[1,0]])


[[1 2]
 [4 5]
 [7 8]]
4
[7 5]
-------
[[4 5]
 [1 2]]


솔직히 `mat[[1,0]]` 이 문장은 잘 이해 안됨.

## 연산

In [29]:
x = np.array([1,2,3])
y = np.array([4,5,6])

# result = np.add(x, y)와 동일.
result = x + y
print(result)

# result = np.subtract(x, y)와 동일.
result = x - y
print(result)

# result = np.multiply(result, x)와 동일.
result = result * x
print(result)

# result = np.divide(result, x)와 동일.
result = result / x
print(result)
# 왜 여기에만 끝에 콤마가 더 들어가 있는가? 아니다. 콤마가 아니라 점 이었음!

print('--------')

mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat3 = np.dot(mat1, mat2)
print('dot product:\n%s' % mat3)


[5 7 9]
[-3 -3 -3]
[-3 -6 -9]
[-3. -3. -3.]
--------
dot product:
[[19 22]
 [43 50]]


## matplotlib

In [30]:
%matplotlib inline

# import keras
# keras.__version__

#pip install matplotlib

import matplotlib as mpl
mpl.__version__

ModuleNotFoundError: No module named 'matplotlib'