In [ ]:
# ml_torch 는 conda 가상 환경임.
# torch 는 pypi 설치임.
!pip install torch

In [10]:
import torch
import numpy as np

In [2]:
rands = torch.randn(2, 3)
ones = torch.ones(2, 3)
zeros = torch.zeros(2, 3)

In [15]:
print(type(ones))

<class 'torch.Tensor'>


In [4]:
a1 = torch.stack((ones, zeros))
print(a1.shape)
a1

torch.Size([2, 2, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
a2 = torch.stack((ones, zeros, ones, zeros))
print(a2.shape)
a2

torch.Size([4, 2, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [6]:
a3 = torch.stack( [ones, zeros, ones] )
print(a3.shape); a3

torch.Size([3, 2, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [11]:
na = np.array([ones, zeros, ones])
a4 = torch.Tensor(na)
print(a4.shape); a4

torch.Size([3, 2, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [13]:
torch.tensor([[1, -1], [1, -1]])

tensor([[ 1, -1],
        [ 1, -1]])

In [14]:
l1 = [1, -1]; l2 = [2, -2]
torch.tensor([l1, l2])

tensor([[ 1, -1],
        [ 2, -2]])

In [17]:
t1 = torch.tensor([1,2]); t2 = torch.tensor([3,4]);
torch.tensor([t1, t2])

TypeError: only integer tensors of a single element can be converted to an index

In [20]:
t1 = torch.tensor([1]); t0 = torch.tensor(0)
t1, t1.shape, t0, t0.shape

(tensor([1]), torch.Size([1]), tensor(0), torch.Size([]))

In [18]:
t1 = torch.tensor([1]); t2 = torch.tensor([3]);
torch.tensor([t1, t2])

tensor([1, 3])