## NumPy 사용자 가이드

numpy 공식 홈페이지의 docs 중 하나인 빠른 시작의 학습 내용을 정리.
전체 내용이 아니라 일부 중요하다고 생각되는 것만 진행했음.

https://numpy.org/doc/stable/user/quickstart.html

2025/3/13

## 배열 생성

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)

# 튜플을 사용할 수도 있다. 시퀀스 이기만 하면 뭐든 상관 없는 듯 함.
b = np.array([(1, 2, 3), (4, 5, 6)])
print(b)
# array([[1, 2, 3],
#        [4, 5, 6]])

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]


In [1]:
d = np.array((1, 2))
print(d)

# 문자열도 시퀀스인데.. 이건 그냥 스칼라로 되어 버린다. 리스트 또는 튜플 만 지원되는 것으로 보인다.
c = np.array('1234')
print(c, c.shape)


NameError: name 'np' is not defined

np.array() 의 첫번째 인자 object 는, 레퍼런스에 명확하게 다음과 같이 기술되어 있다.

- object : array_like
- An array, any object exposing the array interface, an object whose __array__ method returns an array, or any (nested) sequence. If object is a scalar, a 0-dimensional array containing object is returned.

총 네 가지를 얘기하고 있는데..
1. array (아마 np.array 를 말하는 듯)
2. array 인터페이스 객체
3. __array__ 메소드를 구현하고 있고 이 메소드가 array 를 리턴
4. 임의의 (중첩) 시퀀스.

문자열은 시퀀스로 볼 수도 있긴 한데..
아마 array-link 객체에는 문자열은 해당되지 않는 것으로 보인다.

## 기본 연산

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

print(b**2)
print(10 * np.sin(a))
print(a < 35)

[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product
print(A @ B)     # matrix product
print(A.dot(B))  # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [ ]:
##   sum() with axis
#
# 기본적으로 이러한 연산은 모양에 관계없이 숫자 목록인 것처럼 배열에 적용됩니다.
# 그러나 axis 매개변수를 지정하면 배열의 지정된 축을 따라 연산을 적용할 수 있습니다.

b = np.arange(12).reshape(3, 4)
print(b, '\n----')

print(b.sum(axis=0))     # sum of each column
# matrix 전체가 아닌 일부 (열 또는 행)에 대해서만 sum()을 하면
# 그 결과 역시 스칼라가 아닌 1차원의 벡터가 된다.
# axis=0 은 차원 0 이 사라지도록 합계를 계산하라는 말.
print(b.sum(axis=1))     # sum of each column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
----
[12 15 18 21]
[ 6 22 38]


In [ ]:
##   sum() with axis

b = np.arange(24).reshape(2, 3, 4)
print(b, '\n----')

print(b.sum(axis=1)) # 축 1이 제거되면 2차원이 된다.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
----
[[12 15 18 21]
 [48 51 54 57]]


In [ ]:
##  min()

b = np.arange(6).reshape(2, 3)
print(b)
print(b.min(axis=1))     # axis 1 이 제거되어 (2,0) shape 이 됨.

[[0 1 2]
 [3 4 5]]
[0 3]


In [ ]:
##  cumsum()

b = np.arange(6).reshape(2, 3)
print(b)

print(b.sum(axis=1)) # 계산 결과 axis 1이 사라져서 차원이 감소.

# cumsum 은 차원이 줄어들지 않는다. axis 1, 즉 가로 방향으로 누적 합을 계산해 간다.
print(b.cumsum(axis=1))

[[0 1 2]
 [3 4 5]]
[ 3 12]
[[ 0  1  3]
 [ 3  7 12]]


## 범용 함수

In [ ]:
B = np.arange(3)
print(B)

print(np.exp(B))

print(np.sqrt(B))

C = np.array([2., -1, 4])
print(np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


## 인덱싱, 슬라이싱, ..

In [ ]:
##   1차원

a = np.arange(10)**3
print(a)

print('slicing:', a[2:5])

# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print('write to slicing:', a)

print('reversed:', a[::-1])  # reversed a

for i in a:
    print('%.3f' % i**(1 / 3.))

[  0   1   8  27  64 125 216 343 512 729]
slicing: [ 8 27 64]
write to slicing: [1000    1 1000   27 1000  125  216  343  512  729]
reversed: [ 729  512  343  216  125 1000   27 1000    1 1000]
10.000
1.000
10.000
3.000
10.000
5.000
6.000
7.000
8.000
9.000


In [ ]:
##   다차원

# 좌표의 함수로 배열 생성하기. x 가 axis=0, y 가 axis=1
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
print(b)

print(b[2, 3])
print(b[0:5, 1])  # each row in the second column of b
print(b[:, 1])    # equivalent to the previous example
print(b[1:3, :])  # each column in the second and third row of b

print(b[0:3:2, :]) # 연속적이지 않은 rows

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[[ 0  1  2  3]
 [20 21 22 23]]


In [ ]:

b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

연속된 `:` 는 생략할 수도 있음.

예: x가 5차원인 경우.
- `x[1, 2, ...]` is equivalent to `x[1, 2, :, :, :]`
- `x[..., 3]` to `x[:, :, :, :, 3]`
- `x[4, ..., 5, :]` to `x[4, :, :, 5, :]`

In [ ]:
##   dots (...)

c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)

print(c[1, ...])  # same as c[1, :, :] or c[1]

print(c[..., 2])  # same as c[:, :, 2]

(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [ ]:
b = np.arange(6).reshape(3, 2)
for element in b.flat:
    print(element)

0
1
2
3
4
5


# Less Basic

https://numpy.org/doc/stable/user/quickstart.html#less-basic

이하 생략