https://docs.pytorch.org/docs/stable/torch.html#

docs/torch

이 폴더에 정리된 내용 보다 아래 site 의 내용을 참고하는 것이 더 좋다.
- https://runebook.dev/ko/docs/pytorch/-index-

In [2]:
import torch
torch.__version__

'2.6.0'


# Tensors

## Creating Ops




## Indexing, Slicing, Joining, Mutating Ops

- adjoint
- argwhere
- cat
- concat
- concatenate
- conj
- chunk
- dsplit
- column_stack
- dstack
- gather
- hsplit
- hstack
- index_add
- index_copy
- index_reduce
- index_select
- masked_select
- movedim
- moveaxis
- narrow
- narrow_copy
- nonzero
- permute
- reshape
- row_stack
- select
- scatter
- diagonal_scatter
- select_scatter
- slice_scatter
- scatter_add
- scatter_reduce
- split
- squeeze
- stack
- swapaxes
- swapdims
- t
- take
- take_along_dim
- tensor_split
- tile
- transpose
- unbind
- unravel_index



### unsqueeze


In [ ]:
x = torch.tensor([1, 2, 3, 4])

print(torch.unsqueeze(x, 0))
# tensor([[ 1,  2,  3,  4]])

print(torch.unsqueeze(x, 1))

print(torch.unsqueeze(x, -1)) # 끝에서부터 카운팅. -1은 가장 마지막 차원.
print(torch.unsqueeze(x, -2))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2, 3, 4]])



- vsplit
- vstack
- where


----


Accelerators
Generators
Random sampling
Serialization
Parallelism
Locally disabling gradient computation
Math operations
Utilities
Symbolic Numbers
Export Path
Control Flow
Optimizations
Operator Tags